name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: autoformatter
        uses: mezgoodle/auto-formatter@v1.0
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        python: true
        md: false
        css: false
        html: true
