name: CI

on:
  push:
    branches: [ master ]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: autoformatter
        uses: mezgoodle/auto-formatter@v0.1.14
    env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
        python: true
        md: true
        css: true
        html: true
